### ISSUE TITLE
Static link for escapi.dll?

### ISSUE THREAD

**Issue by WhoseTheNerd** [jarikomppa/escapi#12]
I really like your library, but only one problem. If i want to make program one file executable then it cannot be single file, because library requires dll. Can you compile dll as .lib or something that i can link staticly.

**Comment by jarikomppa** [comment]
The whole point of escapi is the dynamic linking.

If static linking is used, you also need to link to the various windows
media libraries that escapi relies on, which is precisely the thing it was
made to avoid.

**Comment by WhoseTheNerd** [comment]
Thanks for the anwser.
