### ISSUE TITLE
Version 2.1

### ISSUE THREAD

**Issue by srstrong** [jarikomppa/escapi#15]
Not so much of an issue, more a request - form the readme, it looks like version 2 was targeting DirectShow rather than MediaFoundation - is the v2 code available anywhere, since I have a DirectShow device that I need to capture from...

**Comment by jarikomppa** [comment]
Sorry, it's not available. It's a mess, and furthermore dependent on some
microsoft SDK code that doesn't seem to be part of their SDKs anymore.

**Comment by srstrong** [comment]
Ok, no problem
