### ISSUE TITLE
Escapi library not showing any output

### ISSUE THREAD

**Issue by Aman-Kaushik13** [jarikomppa/escapi#20]
Hi, I am using the escapi binaries for my project....... I have created a Windows Desktop wizard empty application using visual studio 16 and added the escapi.h, escapi.cpp, and escapi.dll to my project but when I run my project it does not show anything and it does not even detect my camera....where should I add the escapi.dll or do I need to do anything else to make it work .

**Comment by danilogr** [comment]
Take a look at the sample code included with this project. Your Windows Desktop project has to use the functions in `escapi.h` to open a camera, capture a frame, and then you will have to write code to display that frame using the WinForms API.

If this is your first time doing something like this, I would recommend cloning this repository and modifying one of the sample projects - `ogl` and `multicap` are good starting points.
