### ISSUE TITLE
How to convert the buffer values into RGB?

### ISSUE THREAD

**Issue by SeaN0X** [jarikomppa/escapi#27]
While viewing the result buffer with the code below:

 ```
for(int i=0; i< (320 * 240); i++){
	printf("%i\n",capture.mTargetBuf[i]);
}
```

i've noticed outputs like those:

```
...
10660013
10331309
10134189
10002346
10002348
9870508
9739181
...
```

I haven't really figured out what they mean, i know they change from low to high depending from the brightness the camera camera captures, but i am not sure how to turn them into an RGB somehow, i did tried checking the examples, i checked the multicap folder and code, but i am really not smart enough to understand those complicated math operations with the buffer, so i am not sure how to replicate it nor how it works.

i ask here if anyone know a way to do this, prefferably not using that complex code, TIA.

**Comment by SeaN0X** [comment]
i asked chatgpt about DirectShow API usage, and found out the RGB is encoded as RGB24, basically the RGB is encoded as a 3 bytes integer, so i could decode it using the following code:

```c
typedef struct {
    unsigned char r;
    unsigned char g;
    unsigned char b;
} RGB;

RGB convertIntToRGB(unsigned int rgb24) {
    RGB color;
    color.r = (rgb24 >> 16) & 0xFF; // Extracts the red byte
    color.g = (rgb24 >> 8) & 0xFF;  //Extracts the green byte
    color.b = rgb24 & 0xFF;         // Extracts the blue byte
    return color;
}

int main() {
...
for(int i=0; i< (320 * 240); i++){
    unsigned int rgb24 = (int)capture.mTargetBuf[i]; 
    RGB color = convertIntToRGB(rgb24);

    printf("R=%d G=%d B=%d\n", color.r, color.g, color.b);
}
 ...
}
```

i tested it out blocking light from reaching my camera, 0 RGB on the outputs, then i pointed a flashlight to my camera and got 255 RGB on the outputs, it works :D

**Comment by defini7** [comment]
You could also use unions:
`
union RGBint
{
	int rgb;
	uint8_t c[4];
};
`
and then
`
RGBint col;
col.rgb = mTargetBuf[i];

uint8_t r = c[2];
uint8_t g = c[1];
uint8_t b = c[0];
`
