### ISSUE TITLE
Is the build script still working?

### ISSUE THREAD

**Issue by application-developer-DA** [jarikomppa/escapi#3]
Hi, I tried to build the project (used it as a Rust dependency), but it failed at the last step (copying) of `build.rs`, I tried to download the project and build it on my local machine as a separate crate, but it still fails.

I tried to uncomment the last line (where the copy is done) and now it works. Seems like the `build.rs` do not always build the DLL, even though the `cmd.output().expect(...);` does not fail.

By the way, I think that it makes sense to build a static library when building a library for Rust, in this case the users of the crate do not need to ship a DLL with their executable/library.

**Comment by jarikomppa** [comment]
Hi, unfortunately I have no idea about the rust stuff. I assume it has
worked at some point, and if it has stopped working, the problem is on rust
side, not the script's side, as the script hasn't changed. =)

Pull requests are welcome.
