### ISSUE TITLE
The captured frame format

### ISSUE THREAD

**Issue by application-developer-DA** [jarikomppa/escapi#4]
I think it would be nice to update the documentation a bit, currently it does not mention the format of the returned frame. Is it the same format regardless of the camera? If so, does it mean that the conversion is applied to the captured frame before the frame is returned to the user? Would it make sense to allow user to specify the format of the captured frame (so that we can skip the conversion to improve the capturing performance)?

**Comment by jarikomppa** [comment]
Escapi always requests the same format from the camera. If the camera
doesn't support the format, the device will simply fail.

If you want to specify some specific format, escapi is probably not what
you're looking for.

**Comment by application-developer-DA** [comment]
Ah, ok. I've just noticed that there are some conversions mentioned in the C++ version, so I thought that they are done.

What is the format which escapi requests from the camera? Is it BGRA? (I guess it's BGRA based on the Python examples)

P.S.: It seems that there are no other libraries for camera capturing in Windows among Rust crates (OpenCV crate is not compilable under Windows, so I don't count it), so it seems quite an interesting thing, I've already started to improve the Rust bindings (I hope to finish it by tomorrow and send a pull request). How complex would be to add support for enumerating the available formats and capturing in a specified format?

**Comment by jarikomppa** [comment]
You would be better off writing your own
directshow/directmedia/directwhatever wrapper. Escapi is meant to be
minimal.

**Comment by application-developer-DA** [comment]
Hm. Ok. In my opinion escapi could have remained as simple as it is while being versatile. Moreover, it could extend the user base and it would be a good opportunity to refactor both the C++ library (there are quite a few things to improve there, especially in the error handling and external interface) and bindings.

Just so that we can close this issue, can you please confirm if my understanding is correct (there is no documentation, so I tried to figure out how it works based on the source codes of the bindings):

1. Escapi tries to capture in the resolution specified by user. If the actual resolution (native resolution) does not correspond to the requested resolution, escapi will scale the frame to the request size (I made this conclusion based on the comments from Rust example).
2. Escapi always tries to capture a frame in one specific format (i.e. BGRA frame), if the format is not supported by the camera, escapi will fail immediately (I made this conclusion based on the Python example and your comments above).

**Comment by jarikomppa** [comment]
Hi,

You seem to have strong opinions about this, so this might be the perfect
opportunity to make a fork, give it a new name, and keep developing it
forward, That's the good side of open source =)

As for your questions;

1. AFAIR, escapi tries to take the resolution or some resolution higher
than requested, and then point-sample rescales to the wanted resolution.
2. Yes. If there are several devices, some other device may still work.

**Comment by application-developer-DA** [comment]
Ok, thanks.

I'm closing this issue as I think that my initial question (the reason why I created this issue) has been answered.
